/// Parity check against the official `pocket-tts` PyTorch package
/// (`pip install pocket-tts`, kyutai-labs/pocket-tts).
///
/// At temperature 0.0 the flow-matching sampler's noise has std = 0.0**0.5 = 0
/// in *both* the official model (pocket_tts/models/flow_lm.py:157-160) and this
/// port (`SimpleRng::new` in tts_generate.rs, `std = temperature.sqrt()`), so
/// generation is deterministic in both without needing to match RNG streams.
///
/// Fixtures (`tests/fixtures/parity/<language>.json`) were generated by running
/// the same text/voice/temperature through `TTSModel.load_model(language=...)`
/// (see the reference generation script, not checked into this repo) and
/// recording total frame/sample counts plus first/last-5 frame PCM stats.
///
/// Known gap, not yet closed: the official package's
/// `generate_audio_stream` adds +2 to the text-length-based `frames_after_eos`
/// guess before applying it (pocket_tts/models/tts_model.py:720-731); this
/// port's `prepare_text_prompt` (crates/tts-core/src/tts_model.rs) does not.
/// That alone would make official runs ~2 frames longer; the actual deltas
/// observed (French: 0, German: -2, Spanish: -4, Portuguese: +3, Italian: -3
/// frames, this port relative to official) are not fully explained by that
/// one constant, so some residual EOS-timing divergence remains
/// uninvestigated. This test therefore checks total duration within a loose
/// 20% tolerance, not frame-exact agreement -- tightening it is follow-up
/// work, not a claim already met.
///
/// Requires locally-downloaded model/tokenizer/voice files (gated Hub repo);
/// point at them with env vars, or the test is skipped. `english` is
/// intentionally excluded: the official package's `language="english"` alias
/// resolves to the newer `english_2026-09` checkpoint, not the older root
/// checkpoint this repo currently ships as `pocket-tts-q8_0.gguf`, so a
/// same-checkpoint comparison for English needs the newer checkpoint
/// quantized first (see the run doc's open items).
use serde::Deserialize;
use std::path::Path;
use std::process::Command;

#[derive(Deserialize)]
struct ParityFixture {
    #[allow(dead_code)]
    language: String,
    text: String,
    total_samples: usize,
}

struct Case {
    language: &'static str,
    model_env: &'static str,
    tokenizer_env: &'static str,
    voice_env: &'static str,
}

const CASES: &[Case] = &[
    Case { language: "french", model_env: "POCKET_TTS_FR_MODEL", tokenizer_env: "POCKET_TTS_FR_TOKENIZER", voice_env: "POCKET_TTS_FR_VOICE" },
    Case { language: "german", model_env: "POCKET_TTS_DE_MODEL", tokenizer_env: "POCKET_TTS_DE_TOKENIZER", voice_env: "POCKET_TTS_DE_VOICE" },
    Case { language: "spanish", model_env: "POCKET_TTS_ES_MODEL", tokenizer_env: "POCKET_TTS_ES_TOKENIZER", voice_env: "POCKET_TTS_ES_VOICE" },
    Case { language: "portuguese", model_env: "POCKET_TTS_PT_MODEL", tokenizer_env: "POCKET_TTS_PT_TOKENIZER", voice_env: "POCKET_TTS_PT_VOICE" },
    Case { language: "italian", model_env: "POCKET_TTS_IT_MODEL", tokenizer_env: "POCKET_TTS_IT_TOKENIZER", voice_env: "POCKET_TTS_IT_VOICE" },
];

fn release_binary() -> Option<std::path::PathBuf> {
    // Built by `cargo build --release --example tts_generate -p tts-core`.
    let candidates = [
        "target/release/examples/tts_generate",
        "../target/release/examples/tts_generate",
        "../../target/release/examples/tts_generate",
    ];
    candidates.iter().map(Path::new).find(|p| p.exists()).map(|p| p.to_path_buf())
}

#[test]
#[ignore = "requires locally downloaded per-language model/tokenizer/voice files and a release build"]
fn official_parity_total_duration() {
    let Some(bin) = release_binary() else {
        eprintln!("SKIP: release tts_generate binary not found, run cargo build --release --example tts_generate -p tts-core first");
        return;
    };

    let mut any_ran = false;
    for case in CASES {
        let (Ok(model), Ok(tokenizer), Ok(voice)) = (
            std::env::var(case.model_env),
            std::env::var(case.tokenizer_env),
            std::env::var(case.voice_env),
        ) else {
            eprintln!("SKIP {}: set {}, {}, {}", case.language, case.model_env, case.tokenizer_env, case.voice_env);
            continue;
        };

        let fixture_path = format!("tests/fixtures/parity/{}.json", case.language);
        let fixture: ParityFixture =
            serde_json::from_str(&std::fs::read_to_string(&fixture_path).unwrap_or_else(|e| {
                panic!("failed to read {fixture_path}: {e}")
            }))
            .unwrap_or_else(|e| panic!("failed to parse {fixture_path}: {e}"));

        any_ran = true;
        let output_wav = format!("/tmp/official_parity_{}.wav", case.language);
        let output = Command::new(&bin)
            .args([
                "--model", &model,
                "--tokenizer", &tokenizer,
                "--voice", &voice,
                "--text", &fixture.text,
                "--output", &output_wav,
                "--temperature", "0.0",
            ])
            .output()
            .expect("failed to run tts_generate");

        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(output.status.success(), "{}: tts_generate failed:\n{stderr}", case.language);
        assert!(!stderr.contains("nan=1") && !stderr.contains("inf=1"), "{}: NaN/Inf in output", case.language);

        let total_samples: usize = stderr
            .lines()
            .find_map(|l| l.trim().strip_prefix("total_samples: "))
            .unwrap_or_else(|| panic!("{}: total_samples not found in output", case.language))
            .parse()
            .unwrap();

        let ratio = total_samples as f64 / fixture.total_samples as f64;
        println!(
            "{}: rust={} official={} ratio={:.2}",
            case.language, total_samples, fixture.total_samples, ratio
        );
        assert!(
            (0.8..=1.2).contains(&ratio),
            "{}: total_samples {} vs official {} (ratio {:.2}) outside the documented 20% tolerance",
            case.language, total_samples, fixture.total_samples, ratio
        );
    }

    if !any_ran {
        eprintln!("SKIP: no per-language env vars set, nothing to compare");
    }
}
