/// Parity check against the official `pocket-tts` PyTorch package
/// (`pip install pocket-tts`, kyutai-labs/pocket-tts).
///
/// At temperature 0.0 the flow-matching sampler's noise has std = 0.0**0.5 = 0
/// in *both* the official model (pocket_tts/models/flow_lm.py:157-160) and this
/// port (`SimpleRng::new` in tts_generate.rs, `std = temperature.sqrt()`), so
/// generation is deterministic in both without needing to match RNG streams.
///
/// Fixtures (`tests/fixtures/parity/<language>.json`) were generated by running
/// the same text/voice/temperature through `TTSModel.load_model(language=...)`
/// (see the reference generation script, not checked into this repo) and
/// recording total frame/sample counts plus first/last-5 frame PCM stats.
///
/// EOS/frame-count bugs (off-by-one countdown order, missing `+2` on the
/// text-length guess, missing `_MIN_FRAMES_BEFORE_EOS` gate) are fixed as of
/// this test; the frame-count tolerance below is *not* zero because a
/// residual per-step EOS-logit divergence remains, confirmed on unquantized
/// F32 weights (not just Q8_0): a flow-LM-only run (`eos_probe`, no Mimi)
/// against the official French safetensors checkpoint puts the raw EOS
/// logit within ~0.04 of the official value at step 0, but already ~1.5
/// off by step 1, and the first EOS crossing 3 steps later than official
/// (Rust step 36 vs. official step 33 for the French fixture text/voice,
/// both temperature 0). So this gap is not simply quantization noise; its
/// exact source (RoPE convention and the frequency formula were checked
/// against `pocket_tts/modules/rope.py` and match) is not yet isolated --
/// see the parity run doc for the measured per-language deltas this bound
/// is based on. This test checks frame-count within that measured bound,
/// not frame-exact agreement.
///
/// Requires locally-downloaded model/tokenizer/voice files (gated Hub repo);
/// point at them with env vars, or the test is skipped. `english` is
/// intentionally excluded: the official package's `language="english"` alias
/// resolves to the newer `english_2026-09` checkpoint, not the older root
/// checkpoint this repo currently ships as `pocket-tts-q8_0.gguf`, so a
/// same-checkpoint comparison for English needs the newer checkpoint
/// quantized first (see the run doc's open items).
///
/// Per-step latent max-abs-diff bound (proposed follow-up, not implemented
/// here): would need fixtures regenerated with raw per-step flow-LM latents,
/// not just decoded-audio stats; the first decoded PCM frame is too close to
/// Mimi's own convolution warm-up silence to be a robust proxy (measured:
/// Rust's frame 0 for the French fixture has |min|/|max| about 20x smaller
/// than the official fixture's frame 0, despite both being nearly silent).
use serde::Deserialize;
use std::path::Path;
use std::process::Command;

#[derive(Deserialize)]
struct ParityFixture {
    #[allow(dead_code)]
    language: String,
    text: String,
    total_samples: usize,
    num_frames: usize,
}

/// Frame-count tolerance, in frames, replacing the earlier 20%-duration
/// ratio. Measured post-fix deltas (rust total frames - official total
/// frames, this session, Q8_0 GGUF, temperature 0.0): French +1, German -1,
/// Spanish -3, Portuguese +4, Italian -2. Max observed is 4; this leaves a
/// documented margin of 1 frame rather than pinning the exact max.
const FRAME_COUNT_TOLERANCE: i64 = 5;

struct Case {
    language: &'static str,
    model_env: &'static str,
    tokenizer_env: &'static str,
    voice_env: &'static str,
}

const CASES: &[Case] = &[
    Case { language: "french", model_env: "POCKET_TTS_FR_MODEL", tokenizer_env: "POCKET_TTS_FR_TOKENIZER", voice_env: "POCKET_TTS_FR_VOICE" },
    Case { language: "german", model_env: "POCKET_TTS_DE_MODEL", tokenizer_env: "POCKET_TTS_DE_TOKENIZER", voice_env: "POCKET_TTS_DE_VOICE" },
    Case { language: "spanish", model_env: "POCKET_TTS_ES_MODEL", tokenizer_env: "POCKET_TTS_ES_TOKENIZER", voice_env: "POCKET_TTS_ES_VOICE" },
    Case { language: "portuguese", model_env: "POCKET_TTS_PT_MODEL", tokenizer_env: "POCKET_TTS_PT_TOKENIZER", voice_env: "POCKET_TTS_PT_VOICE" },
    Case { language: "italian", model_env: "POCKET_TTS_IT_MODEL", tokenizer_env: "POCKET_TTS_IT_TOKENIZER", voice_env: "POCKET_TTS_IT_VOICE" },
];

fn release_binary() -> Option<std::path::PathBuf> {
    // Built by `cargo build --release --example tts_generate -p tts-core`.
    let candidates = [
        "target/release/examples/tts_generate",
        "../target/release/examples/tts_generate",
        "../../target/release/examples/tts_generate",
    ];
    candidates.iter().map(Path::new).find(|p| p.exists()).map(|p| p.to_path_buf())
}

#[test]
#[ignore = "requires locally downloaded per-language model/tokenizer/voice files and a release build"]
fn official_parity_total_duration() {
    let Some(bin) = release_binary() else {
        eprintln!("SKIP: release tts_generate binary not found, run cargo build --release --example tts_generate -p tts-core first");
        return;
    };

    let mut any_ran = false;
    for case in CASES {
        let (Ok(model), Ok(tokenizer), Ok(voice)) = (
            std::env::var(case.model_env),
            std::env::var(case.tokenizer_env),
            std::env::var(case.voice_env),
        ) else {
            eprintln!("SKIP {}: set {}, {}, {}", case.language, case.model_env, case.tokenizer_env, case.voice_env);
            continue;
        };

        let fixture_path = format!("tests/fixtures/parity/{}.json", case.language);
        let fixture: ParityFixture =
            serde_json::from_str(&std::fs::read_to_string(&fixture_path).unwrap_or_else(|e| {
                panic!("failed to read {fixture_path}: {e}")
            }))
            .unwrap_or_else(|e| panic!("failed to parse {fixture_path}: {e}"));

        any_ran = true;
        let output_wav = format!("/tmp/official_parity_{}.wav", case.language);
        let output = Command::new(&bin)
            .args([
                "--model", &model,
                "--tokenizer", &tokenizer,
                "--voice", &voice,
                "--language", case.language,
                "--text", &fixture.text,
                "--output", &output_wav,
                "--temperature", "0.0",
            ])
            .output()
            .expect("failed to run tts_generate");

        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(output.status.success(), "{}: tts_generate failed:\n{stderr}", case.language);
        assert!(!stderr.contains("nan=1") && !stderr.contains("inf=1"), "{}: NaN/Inf in output", case.language);

        let total_steps: usize = stderr
            .lines()
            .find_map(|l| l.trim().strip_prefix("total_steps: "))
            .unwrap_or_else(|| panic!("{}: total_steps not found in output", case.language))
            .parse()
            .unwrap();
        let total_samples: usize = stderr
            .lines()
            .find_map(|l| l.trim().strip_prefix("total_samples: "))
            .unwrap_or_else(|| panic!("{}: total_samples not found in output", case.language))
            .parse()
            .unwrap();

        let frame_delta = total_steps as i64 - fixture.num_frames as i64;
        println!(
            "{}: rust_frames={} official_frames={} delta={} rust_samples={} official_samples={}",
            case.language, total_steps, fixture.num_frames, frame_delta, total_samples, fixture.total_samples
        );
        assert!(
            frame_delta.abs() <= FRAME_COUNT_TOLERANCE,
            "{}: {} frames vs official {} frames (delta {}) outside the documented {}-frame tolerance",
            case.language, total_steps, fixture.num_frames, frame_delta, FRAME_COUNT_TOLERANCE
        );
    }

    if !any_ran {
        eprintln!("SKIP: no per-language env vars set, nothing to compare");
    }
}
