[workspace]
members = ["crates/tts-core", "crates/tts-wasm", "crates/kitten-core", "crates/kitten-wasm"]
resolver = "3"

[workspace.dependencies]
# WASM support
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console", "Response", "Request", "RequestInit", "RequestMode"] }
console_error_panic_hook = "0.1"
getrandom = { version = "0.3", default-features = false }

# Core
anyhow = "1.0"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
byteorder = "1.5"

[patch.crates-io]
candle-core = { git = "https://github.com/ilnmtlbnm/candle.git", branch = "wasm-simd-opt" }
candle-nn = { git = "https://github.com/ilnmtlbnm/candle.git", branch = "wasm-simd-opt" }

[profile.release]
lto = "fat"
codegen-units = 1

[profile.release-wasm]
inherits = "release"
opt-level = "s"
